{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "58ecc1a8",
   "metadata": {},
   "outputs": [],
   "source": [
    "dict_candidatos_2020 = [\n",
    "    {\"SQ_CANDIDATO\": 160000802916, \"Nome_Completo\": \"ADELAR TEIXEIRA DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ADELAR TEIXEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915935, \"Nome_Completo\": \"ADEMIR DE BRAZ\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ADEMIR DE BRAZ\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704240, \"Nome_Completo\": \"ADRIANA PATRICIA VIANA ROCHA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ADRIANA PATRICIA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704104, \"Nome_Completo\": \"ADRIANO RODRIGO CORDEIRO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ADRIANO CORDEIRO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704241, \"Nome_Completo\": \"AIRTON EMMANUEL PITTA FERREIRA QUADROS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"AIRTON QUADROS\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002243, \"Nome_Completo\": \"ALEX YORAN MACHADO GUEBER\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ALEX YORAN MACHADO GUEBER\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802909, \"Nome_Completo\": \"ALEXANDRE DOS SANTOS SCHIMITS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ALEXANDRE SCHIMITS\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138581, \"Nome_Completo\": \"ALEXANDRE FERREIRA LOPES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ALEXANDRE LOPES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048541, \"Nome_Completo\": \"ALEXANDRE WALTER DRISCHEL\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ALEXANDRE DRISCHEL\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802921, \"Nome_Completo\": \"ALEXSANDRO LINHARES PEREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ALEXSANDRO PEREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761728, \"Nome_Completo\": \"ALEXSANDRO NARCISO DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ALEXSANDRO NARCISO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761737, \"Nome_Completo\": \"ALINE CORREIA OLIVERI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ALINE OLIVERI\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048543, \"Nome_Completo\": \"ALTAIR PROENCA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ALTAIR PROENCA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001140187, \"Nome_Completo\": \"ALVANTINO DA ROSA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ALVANTINO DA ROSA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704106, \"Nome_Completo\": \"ALVARO EDUARDO DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ALVARO DOS SANTOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685746, \"Nome_Completo\": \"ANA MARIA DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANA MARIA DA SILVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137894, \"Nome_Completo\": \"ANASTACIO SALVADOR ALVES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANASTACIO ALVES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761730, \"Nome_Completo\": \"ANDREA DE FREITAS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANDREA DE FREITAS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947242, \"Nome_Completo\": \"ANDRÉ ALVES ARRAIS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANDRÉ ALVES ARRAIS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704182, \"Nome_Completo\": \"ANGELA NAZARETH MARTINS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANGELA MARTINS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685754, \"Nome_Completo\": \"ANIRTON NONATO DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANIRTON NONATO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761706, \"Nome_Completo\": \"ANTENOR JOSÉ DOMINICO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANTENOR DOMINICO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704246, \"Nome_Completo\": \"ANTONIA ALAIR UCHOA SOBRINHO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANTONIA SOBRINHO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138585, \"Nome_Completo\": \"ANTONIO APARECIDO GONZALES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANTONIO GONZALES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048544, \"Nome_Completo\": \"ANTONIO CARLOS LIMA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANTONIO LIMA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002249, \"Nome_Completo\": \"ANTONIO CARLOS NASS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANTONIO NASS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802923, \"Nome_Completo\": \"ANTONIO FRANCISCO DE ALMEIDA JUNIOR\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANTONIO FRANCISCO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002232, \"Nome_Completo\": \"ANTONIO GONZAGA BRITO DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANTONIO GONZAGA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002240, \"Nome_Completo\": \"ANTONIO ROBERTO ZUCCHI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ANTONIO ZUCCHI\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137902, \"Nome_Completo\": \"APARECIDA ELIZABETH SILVA LIMA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"APARECIDA LIMA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048526, \"Nome_Completo\": \"APARECIDO FERREIRA COSTA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"APARECIDO COSTA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138586, \"Nome_Completo\": \"ARMANDO GOMES BENTANCOURT\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ARMANDO BENTANCOURT\"},\n",
    "    {\"SQ_CANDIDATO\": 160000803045, \"Nome_Completo\": \"ARNALDO PEREIRA DA SILVA JUNIOR\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ARNALDO JUNIOR\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761735, \"Nome_Completo\": \"AUDINOR SILVERIO DE BARROS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"AUDINOR BARROS\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002233, \"Nome_Completo\": \"BENICIO CAVALCANTE MOREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"BENICIO MOREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761707, \"Nome_Completo\": \"BRUNO CESAR KAEFER PEREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"BRUNO KAEFER\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138572, \"Nome_Completo\": \"BRUNO SILVEIRA DE LIMA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"BRUNO SILVEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802933, \"Nome_Completo\": \"CARLA ELISA MONTANARIN\", \"Cargo\": \"PREFEITO\", \"Apelido\": \"CARLA MONTANARIN\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802919, \"Nome_Completo\": \"CARLOS ALEXANDRE DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CARLOS ALEXANDRE\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886149, \"Nome_Completo\": \"CARLOS GOMES DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CARLOS GOMES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001047472, \"Nome_Completo\": \"CARLOS RODRIGUES ALVES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CARLOS RODRIGUES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802915, \"Nome_Completo\": \"CELIA VIEIRA DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CELIA VIEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048539, \"Nome_Completo\": \"CELIO DA SILVA CASTRO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CELIO DA SILVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802918, \"Nome_Completo\": \"CELSO GOMES DE CARVALHO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CELSO GOMES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704100, \"Nome_Completo\": \"CICERO SOARES DE OLIVEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CICERO TERRAPLANAGEM\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947233, \"Nome_Completo\": \"CILMARA APARECIDA DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CILMARA APARECIDA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048545, \"Nome_Completo\": \"CIRENE BATISTA CORREA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CIRENE CORREA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138575, \"Nome_Completo\": \"CLARICE TEREZINHA LIMA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CLARICE LIMA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048542, \"Nome_Completo\": \"CLAUDINEI BELARMINO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CLAUDINEI BELARMINO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048536, \"Nome_Completo\": \"CLAUDIO CEZAR DE SOUZA COTA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CLAUDIO COTA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704102, \"Nome_Completo\": \"CLAUDIO NEI SINKES DE PAULA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SARGENTO SINKES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685750, \"Nome_Completo\": \"CLEDIANE SILVA RODRIGUES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CLEDIANE RODRIGUES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802912, \"Nome_Completo\": \"CLEIDE BARBOSA DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CLEIDE SILVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915938, \"Nome_Completo\": \"CLEITON VARGAS FRANCO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CLEITON FRANCO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002246, \"Nome_Completo\": \"CLEODECI DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CLEODECI DA SILVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137900, \"Nome_Completo\": \"CLEOMAR PONTES MACEDO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CLEOMAR MACEDO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915936, \"Nome_Completo\": \"CLEOMARY BESCOROVAINE\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CLEOMARY BESCOROVAINE\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002242, \"Nome_Completo\": \"CLEUDILENE ROBINSON DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CLEUDILENE SANTOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886146, \"Nome_Completo\": \"CLODOALDO SALVADOR\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CLODOALDO SALVADOR\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915941, \"Nome_Completo\": \"CONSUELO DE FATIMA GOMES DA SILVA DE CARVALHO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CONSUELO DE FATIMA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001047476, \"Nome_Completo\": \"CRISTIAN DE SOUZA CARLETO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CRISTIAN CARLETO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048533, \"Nome_Completo\": \"CRISTIAN VICTOR AGUIAR PEREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"CRISTIAN PEREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685762, \"Nome_Completo\": \"DANIEL FLORIANO FERREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"DANIEL FLORIANO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001047471, \"Nome_Completo\": \"DAVI COSTA CRISTO SOBRINHO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"DAVI COSTA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685747, \"Nome_Completo\": \"DEVANIR FELIPPE ALVES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"DEVANIR FELIPPE\"},\n",
    "    {\"SQ_CANDIDATO\": 160000803042, \"Nome_Completo\": \"DIANA FERREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"DIANA FERREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002235, \"Nome_Completo\": \"DILEUZA DE JESUS DE CASTRO KANO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"DILEUZA DE JESUS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886147, \"Nome_Completo\": \"DIVONSIR ROBERTO DOS ANJOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"DIVONSIR ROBERTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704171, \"Nome_Completo\": \"DOLORES CARVALHO DE ARAUJO MAZEPA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"DORINHA MAZEPA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704175, \"Nome_Completo\": \"EDERLEI ANTUNES PEREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EDERLEI PEREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137906, \"Nome_Completo\": \"EDIANE DALO TIBES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EDIANE TIBES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704248, \"Nome_Completo\": \"EDINALVA THEODORO MARTINS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EDINALVA MARTINS\"},\n",
    "    {\"SQ_CANDIDATO\": 160001270475, \"Nome_Completo\": \"EDINEI HONORIO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EDINEI HONORIO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947228, \"Nome_Completo\": \"EDIU ROBERTO FERNANDES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EDIU ROBERTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886144, \"Nome_Completo\": \"EDSON FERREIRA DO NASCIMENTO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EDSON NASCIMENTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001114980, \"Nome_Completo\": \"EDSON RIBEIRO\", \"Cargo\": \"VICE-PREFEITO\", \"Apelido\": \"EDSON RIBEIRO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947237, \"Nome_Completo\": \"EDUARDO AUGUSTO KOWALCZUK ALVES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EDUARDO ALVES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704172, \"Nome_Completo\": \"ELIANE MIRANDA PENTEADO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ELIANE PENTEADO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947239, \"Nome_Completo\": \"ELIO LUZ BARROS PEREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ELIO PEREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704174, \"Nome_Completo\": \"ELIO MOREIRA SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ELIO MOREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761732, \"Nome_Completo\": \"ELISABETE CRISTINA ROSA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ELISABETE ROSA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886157, \"Nome_Completo\": \"ELIZEU MACHADO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ELIZEU MACHADO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704186, \"Nome_Completo\": \"ELIZEU SERAFIM DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ELIZEU SERAFIM\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138571, \"Nome_Completo\": \"ELOIR VIEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ELOIR VIEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048534, \"Nome_Completo\": \"EMANUELL FAVORETO COLLODEL\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EMANUELL COLLODEL\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137907, \"Nome_Completo\": \"EMERSON FABIANO GOMES DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EMERSON FABIANO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685758, \"Nome_Completo\": \"ERNANI WINTER\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ERNANI WINTER\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002245, \"Nome_Completo\": \"ESMAIR XAVIER DE SOUZA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ESMAIR SOUZA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001265380, \"Nome_Completo\": \"ESTHER ENES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ESTHER ENES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704099, \"Nome_Completo\": \"EVANDRO DA ROCHA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EVANDRO DA ROCHA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915943, \"Nome_Completo\": \"EVERTON JURANDIR PEREIRA DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EVERTON JURANDIR\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137903, \"Nome_Completo\": \"FABIANA RIBEIRO DE PAULO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"FABIANA RIBEIRO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685760, \"Nome_Completo\": \"FABIANO MORO WALTRICK\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"FABIANO WALTRICK\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002239, \"Nome_Completo\": \"FELIPE CALIXTO DACAL\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"FELIPE CALIXTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048530, \"Nome_Completo\": \"FRANCIELE ANTUNES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"FRANCIELE ANTUNES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001114979, \"Nome_Completo\": \"GABRIEL JORGE SAMAHA\", \"Cargo\": \"PREFEITO\", \"Apelido\": \"GABÃO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685748, \"Nome_Completo\": \"GABRIEL RICHARD LICKFELD\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"GABRIEL LICKFELD\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685753, \"Nome_Completo\": \"GELSON CHATOSKI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"GELSON CHATOSKI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704236, \"Nome_Completo\": \"GELSON DA SILVA CAMARGO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"GELSON DA SILVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137905, \"Nome_Completo\": \"GERSON LUIS HORNES FERRARI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"GERSON FERRARI\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002244, \"Nome_Completo\": \"GILMAR LUIS CORDEIRO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"GILMAR CORDEIRO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001047473, \"Nome_Completo\": \"GISELE LOPES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"GISELE LOPES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137898, \"Nome_Completo\": \"GISELE TIERA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"GISELE TIERA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704114, \"Nome_Completo\": \"GUANAIR DENILSON GARCIA DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"PASTOR GUANAIR\"},\n",
    "    {\"SQ_CANDIDATO\": 160000783929, \"Nome_Completo\": \"GUERINO VARELA DA SILVA FILHO\", \"Cargo\": \"VICE-PREFEITO\", \"Apelido\": \"GUERINO VARELA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001272039, \"Nome_Completo\": \"GUSTAVO LIMA DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"GUSTAVO LIMA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048538, \"Nome_Completo\": \"HELCIO MURILO LOPPNOW\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"HELCIO LOPPNOW\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704098, \"Nome_Completo\": \"HELIO DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"HELIO DA SILVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761704, \"Nome_Completo\": \"HILARIO ANTONIO DE SOUZA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"HILARIO SOUZA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761705, \"Nome_Completo\": \"IARA DE OLIVEIRA LASCHEWITZ\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"IARA LASCHEWITZ\"},\n",
    "    {\"SQ_CANDIDATO\": 160001267129, \"Nome_Completo\": \"IGOR FERREIRA MENEZES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"IGOR MENEZES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886151, \"Nome_Completo\": \"ILCE HELGA SCHMIDT ARAUJO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ILCE ARAUJO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761718, \"Nome_Completo\": \"ILMA TEAGO ROCHA POTERIKO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ILMA POTERIKO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138569, \"Nome_Completo\": \"ILSON FERMINO LOPES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ILSON FERMINO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704179, \"Nome_Completo\": \"IRMA SALETE GRAFF\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"IRMA SALETE\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704185, \"Nome_Completo\": \"ISAIAS MAGARI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ISAIAS MAGARI\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138574, \"Nome_Completo\": \"ISRAEL ANTONIO HIPOLITO ANTUNES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ISRAEL ANTONIO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915948, \"Nome_Completo\": \"IVALDO DE SOUZA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"IVALDO DE SOUZA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704184, \"Nome_Completo\": \"IVAN ROBERTO VICENTE ALVES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"IVAN ALVES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001140182, \"Nome_Completo\": \"JAIRO BENEDITO TEODORO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JAIRO TEODORO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947227, \"Nome_Completo\": \"JAIRO NOGUEIRA GOMES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JAIRO GOMES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137908, \"Nome_Completo\": \"JAIRO REMI TIEMANN\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JAIRO TIEMANN\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947238, \"Nome_Completo\": \"JANDERSON CORDEIRO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JANDERSON CORDEIRO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000751350, \"Nome_Completo\": \"JEAN CARLOS DA VEIGA DOS SANTOS\", \"Cargo\": \"PREFEITO\", \"Apelido\": \"JEAN GALVÃO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947229, \"Nome_Completo\": \"JEREMIAS PEREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JEREMIAS PEREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947240, \"Nome_Completo\": \"JHONY MALZIR DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JHONY SANTOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704239, \"Nome_Completo\": \"JOAO CARLOS DA CONCEIÇÃO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOAO CONCEIÇÃO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802917, \"Nome_Completo\": \"JOAO LUCAS ESSER BOROCZ\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOAO BOROCZ\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685757, \"Nome_Completo\": \"JOAO MARIA DIAS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOAO DIAS\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002250, \"Nome_Completo\": \"JOBSON DO NASCIMENTO MELO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOB NASCIMENTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685759, \"Nome_Completo\": \"JOEL DO CARMO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOEL DO CARMO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704178, \"Nome_Completo\": \"JONAS ARAUJO FAUSTO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JONAS FAUSTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915946, \"Nome_Completo\": \"JORGE LUIS MULLER\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JORGE MULLER\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886153, \"Nome_Completo\": \"JOSE ANTONIO ORSI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOSE ORSI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704181, \"Nome_Completo\": \"JOSE APARECIDO LEITE RODRIGUES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOSE APARECIDO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704188, \"Nome_Completo\": \"JOSE CICERO FIDELIS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MAGUILA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704183, \"Nome_Completo\": \"JOSE EUGENIO HULLER\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"EUGENIO HULLER\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802910, \"Nome_Completo\": \"JOSE GONÇALVES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOSE GONÇALVES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704176, \"Nome_Completo\": \"JOSE HORACIO DE OLIVEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOSE HORACIO DE OLIVEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704250, \"Nome_Completo\": \"JOSE JOEL DE LIMA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOSE LIMA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886150, \"Nome_Completo\": \"JOSE JOGLAIR AZEVEDO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOSE AZEVEDO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761708, \"Nome_Completo\": \"JOSE MACHADO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ZÉ MACHADO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000751351, \"Nome_Completo\": \"JOSE NATAL CANDIDO PEREIRA\", \"Cargo\": \"VICE-PREFEITO\", \"Apelido\": \"NATAL\"},\n",
    "    {\"SQ_CANDIDATO\": 160000671574, \"Nome_Completo\": \"JOSIMAR APARECIDO KNUPP FROES\", \"Cargo\": \"PREFEITO\", \"Apelido\": \"PROFESSOR JOSIMAR\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761709, \"Nome_Completo\": \"JOSMAR CLARO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOSMAR CLARO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761701, \"Nome_Completo\": \"JOSUEL LOPES RIBEIRO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOSUEL RIBEIRO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137896, \"Nome_Completo\": \"JOSÉ CARLOS DE ALMEIDA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOSÉ CARLOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160001072134, \"Nome_Completo\": \"JOSÉ MENDES FILHO\", \"Cargo\": \"PREFEITO\", \"Apelido\": \"JOSÉ FILHO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001140183, \"Nome_Completo\": \"JOÃO ACIR TINESKI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOÃO TINESKI\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002238, \"Nome_Completo\": \"JOÃO CLAUDIO DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOÃO CLAUDIO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915939, \"Nome_Completo\": \"JOÃO DALMIRO PINHEIRO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOÃO PINHEIRO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048611, \"Nome_Completo\": \"JOÃO GUILHERME RIBAS MARTINS\", \"Cargo\": \"PREFEITO\", \"Apelido\": \"JOÃO GUILHERME\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915950, \"Nome_Completo\": \"JOÃO JOSÉ MORAIS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JOÃO MORAIS\"},\n",
    "    {\"SQ_CANDIDATO\": 160001072135, \"Nome_Completo\": \"JOÃO JOSÉ OLIVEIRA MIRANDA\", \"Cargo\": \"VICE-PREFEITO\", \"Apelido\": \"JOÃO MIRANDA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947230, \"Nome_Completo\": \"JUCILEIDE NUNES MARINS COSTA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JUCILEIDE NUNES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802913, \"Nome_Completo\": \"JUCIMARA APARECIDA DE OLIVEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JUCIMARA APARECIDA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138580, \"Nome_Completo\": \"JULIO CESAR DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JULIO DOS SANTOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761736, \"Nome_Completo\": \"JULIO CESAR VICENTE\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"JULIO VICENTE\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761731, \"Nome_Completo\": \"LAFAETE GOMES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LAFAETE GOMES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685756, \"Nome_Completo\": \"LAIRTON FERREIRA DE SANTANA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LAIRTON DO POSTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947235, \"Nome_Completo\": \"LAUDENICE DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LAUDENICE DA SILVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138570, \"Nome_Completo\": \"LEANDRO DE JESUS ROMERO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LEANDRO ROMERO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802925, \"Nome_Completo\": \"LEANDRO SOARES KEKIS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LEANDRO KEKIS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685751, \"Nome_Completo\": \"LENIR OSINSKI DO PRADO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LENIR OSINSKI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704103, \"Nome_Completo\": \"LEONARDO GABRIEL DA SILVA SANCHES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LEONARDO SANCHES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886154, \"Nome_Completo\": \"LEONICI MARIA BARANHIUKI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LEONICI BARANHIUKI\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002247, \"Nome_Completo\": \"LINDALVA DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LINDALVA DOS SANTOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915933, \"Nome_Completo\": \"LINDALVA TABORDA RIBAS CONDEÇO\", \"Cargo\": \"VICE-PREFEITO\", \"Apelido\": \"LINDALVA TABORDA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138583, \"Nome_Completo\": \"LINDOMAR BARJONAS DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LINDOMAR BARJONAS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947234, \"Nome_Completo\": \"LOHANI SCHER\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LOHANI SCHER\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685761, \"Nome_Completo\": \"LUCIANA ASSIS DE SOUZA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUCIANA SOUZA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685749, \"Nome_Completo\": \"LUCIANE PEREIRA FARIA DE SOUZA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUCIANE PEREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761711, \"Nome_Completo\": \"LUCIANO CARVALHO DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUCIANO CARVALHO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704242, \"Nome_Completo\": \"LUCIANO DA COSTA LARA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUCIANO LARA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802911, \"Nome_Completo\": \"LUCIMARA WAGATUMA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUCIMARA WAGATUMA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802920, \"Nome_Completo\": \"LUCIO RENATO RIBEIRO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUCIO RENATO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761717, \"Nome_Completo\": \"LUIS CARLOS DERENIVICK\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUIS DERENIVICK\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138578, \"Nome_Completo\": \"LUIS CARLOS NUNES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUIS NUNES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048531, \"Nome_Completo\": \"LUIS GUSTAVO PIRES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUIS PIRES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761733, \"Nome_Completo\": \"LUIS HENRIQUE FRANCO MARCELLA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUIS MARCELLA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001047475, \"Nome_Completo\": \"LUIZ ALBERTO TONATTO DO SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUIZ TONATTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001140186, \"Nome_Completo\": \"LUIZ ANTONIO SYPRIANO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUIZ SYPRIANO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915949, \"Nome_Completo\": \"LUIZ CARLOS PALIANO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUIZ PALIANO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138584, \"Nome_Completo\": \"LUIZ CARLOS VERGILIO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUIZ VERGILIO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947244, \"Nome_Completo\": \"LUIZA DOS REIS ALVES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"LUIZA ALVES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704232, \"Nome_Completo\": \"MARCELO MARCAL MORINI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARCELINHO DA SAUDE\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886145, \"Nome_Completo\": \"MARCIO ALEXANDRO FAGUNDES FAUSTINO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARCIO FAUSTINO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761729, \"Nome_Completo\": \"MARCOS ANTONIO DE ANDRADES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARCOS ANTONIO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947232, \"Nome_Completo\": \"MARCOS PAULO SOARES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARCOS SOARES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138579, \"Nome_Completo\": \"MARGARETE MARIA DA CRUZ\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARGARETE MARIA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001140184, \"Nome_Completo\": \"MARI SALETE ALVES DO REGO POVIDAIKO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARI SALETE\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704245, \"Nome_Completo\": \"MARIA ELZA GRACIANO SIMÃO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARIA ELZA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704109, \"Nome_Completo\": \"MARIA FERNANDA BUENO DE MELLO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARIA FERNANDA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704173, \"Nome_Completo\": \"MARIA GEOVANE PETRACINSKI TRENTIN\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARIA TRENTIN\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048527, \"Nome_Completo\": \"MARIA LUCIA DO NASCIMENTO HERNASKI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARIA HERNASKI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000803038, \"Nome_Completo\": \"MA])IA SUELI DA ROCHA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARIA SUELI\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137904, \"Nome_Completo\": \"MARIANNA DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARIANNA DOS SANTOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704231, \"Nome_Completo\": \"MARILDO GOMES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARILDO GOMES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886156, \"Nome_Completo\": \"MARILENE LOPES DOS SANTOS MUZI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARILENE MUZI\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048529, \"Nome_Completo\": \"MARISA PEREIRA DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARISA PEREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138573, \"Nome_Completo\": \"MARLI PEACECKI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARLI PEACECKI\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138582, \"Nome_Completo\": \"MARLOS VINICIUS DALLICANI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARLOS DALLICANI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000783928, \"Nome_Completo\": \"MARSHEL HUMBERTO SIQUEIRA SILVA E LIMA\", \"Cargo\": \"PREFEITO\", \"Apelido\": \"MARSHEL LIMA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761719, \"Nome_Completo\": \"MARY IRLEIA ALVES CASTRO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MARY IRLEIA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704110, \"Nome_Completo\": \"MATHEUS RICARDO RECKELBERG\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MATHEUS RECKELBERG\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704247, \"Nome_Completo\": \"MAURICELIA DE OLIVEIRA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MAURICELIA SILVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802914, \"Nome_Completo\": \"MAURILES LONGHINI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MAURILES LONGHINI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704243, \"Nome_Completo\": \"MIGUEL MARCALO BRUDECK SCROBOT\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MIGUEL SCROBOT\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704235, \"Nome_Completo\": \"MILTOM PEREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MILTOM PEREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704116, \"Nome_Completo\": \"MIRIAM PIRES DA SILVA ALMEIDA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MIRIAM PIRES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002231, \"Nome_Completo\": \"MIRTES DE OLIVEIRA DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"MIRTES DE OLIVEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704169, \"Nome_Completo\": \"NADIR DA FONSECA MELO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"NADIR MELO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761702, \"Nome_Completo\": \"NEIDE MARIA CARDOSO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"NEIDE CARDOSO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704115, \"Nome_Completo\": \"NEIVO JOAO BERTUZZI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"NEIVO BERTUZZI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704233, \"Nome_Completo\": \"NELSON FERREIRA GOIS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"NELSON GOIS\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138576, \"Nome_Completo\": \"NELSON PORTES PEREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"NELSON PEREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704238, \"Nome_Completo\": \"NERI PEDRO SCHMITZ\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"NERI SCHMITZ\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137899, \"Nome_Completo\": \"NEUDES DA LUZ SANTANA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"NEUDES SANTANA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915940, \"Nome_Completo\": \"ODAIL JOSE GOMES DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ODAIL SANTOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000671573, \"Nome_Completo\": \"OLIVÉRIO SARAIVA\", \"Cargo\": \"VICE-PREFEITO\", \"Apelido\": \"OLIVÉRIO SARAIVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000803039, \"Nome_Completo\": \"ORLANDO NUNES DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ORLANDO SILVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002248, \"Nome_Completo\": \"OSMAR DOS SANTOS CUBES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"OSMAR CUBES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947231, \"Nome_Completo\": \"PALOMA BUENO DE FREITAS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"PALOMA FREITAS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704111, \"Nome_Completo\": \"PAMELA MARCELA GOMES DA SILVA DE OLIVEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"PAMELA OLIVEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802934, \"Nome_Completo\": \"PASCOAL ROMUALDO BOZZA\", \"Cargo\": \"VICE-PREFEITO\", \"Apelido\": \"PASCOAL ROMUALDO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761720, \"Nome_Completo\": \"PATRICIA ANDIETRA NEZA DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"PATRICIA ANDIETRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704177, \"Nome_Completo\": \"PAULO ROBERTO ALVES DE OLIVEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"PAULO ROBERTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704249, \"Nome_Completo\": \"PEDRO ALCINDO ZARO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"PEDRO ZARO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137895, \"Nome_Completo\": \"PEDRO RAFAEL LIMA DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"PEDRO RAFAEL\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761714, \"Nome_Completo\": \"PEDRO RENATO GARCIA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"PEDRO GARCIA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886158, \"Nome_Completo\": \"PRISCILA BASTOS DE OLIVEIRA VITAL\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"PRISCILAVITAL\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704112, \"Nome_Completo\": \"RAFAEL JOSE SARAIVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"RAFAEL SARAIVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802924, \"Nome_Completo\": \"RAQUEL GOMES ALVES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"RAQUEL ALVES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947243, \"Nome_Completo\": \"RAUL FABIO CARDOSO MATTAR\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"RAUL MATTAR\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048532, \"Nome_Completo\": \"REGINA CELIA DOMBROSKI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"REGINA DOMBROSKI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685764, \"Nome_Completo\": \"REGINA ISABEL CARDOSO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"REGINA CARDOSO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685755, \"Nome_Completo\": \"REGINALDO JOSE BARBOSA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"REGINALDO BARBOSA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048528, \"Nome_Completo\": \"REINALDO LIMA DE OLIVEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"REINALDO OLIVEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886152, \"Nome_Completo\": \"REINALDO MACIEL\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"REINALDO MACIEL\"},\n",
    "    {\"SQ_CANDIDATO\": 160001267128, \"Nome_Completo\": \"REJANE MARIA MIZERKOWSKI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"REJANE MIZERKOWSKI\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048540, \"Nome_Completo\": \"RENATA TAMMY LOGESKI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"RENATA LOGESKI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685763, \"Nome_Completo\": \"RICARDO KLETLINGUER\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"RICARDO KLETLINGUER\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886155, \"Nome_Completo\": \"RODRIGO JOSÉ PIRES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"RODRIGO PIRES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000803037, \"Nome_Completo\": \"RODRIGO MARTINS DA CRUZ\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"RODRIGO CRUZ\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002241, \"Nome_Completo\": \"ROSANGELA APARECIDA DE OLIVEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ROSANGELA OLIVEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947226, \"Nome_Completo\": \"ROSANGELA DE LIMA SOUZA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ROSANGELA SOUZA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704108, \"Nome_Completo\": \"ROSIANE DE OLIVEIRA SILVA ALVES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ROSIANE ALVES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915937, \"Nome_Completo\": \"ROZANGELA VIDAL DOS SANTOS MACHADO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"ROZANGELA MACHADO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761713, \"Nome_Completo\": \"RUI DOS SANTOS NASCIMENTO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"RUI NASCIMENTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704237, \"Nome_Completo\": \"SAMANDA DA SILVA SOARES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SAMANDA SOARES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802922, \"Nome_Completo\": \"SANDRO ROBERTO BRASSANINI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SANDRO BRASSANINI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761734, \"Nome_Completo\": \"SEBASTIÃO BARBOSA LIMA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SEBASTIÃO LIMA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001140185, \"Nome_Completo\": \"SEMÍRAMIS CARVALHO FERREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SEMÍRAMIS FERREIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915944, \"Nome_Completo\": \"SHEILA THEREZINHA DE JESUS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SHEILA JESUS\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048537, \"Nome_Completo\": \"SIDINEI DE CAMARGO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SIDINEI CAMARGO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138577, \"Nome_Completo\": \"SILMARA DE OLIVEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SILMARA OLIVEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915947, \"Nome_Completo\": \"SILMARA DO ROCIO CAMARGO BIZ\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SILMARA BIZ\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802928, \"Nome_Completo\": \"SILVANA PEREIRA COSTA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SILVANA COSTA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704187, \"Nome_Completo\": \"SILVANIA POLETTI\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SILVANIA POLETTI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704105, \"Nome_Completo\": \"SILVIO CORDEIRO FAVORETTO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SILVIO FAVORETTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947241, \"Nome_Completo\": \"SIMONE ZAVADISK\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SIMONE ZAVADISK\"},\n",
    "    {\"SQ_CANDIDATO\": 160000803044, \"Nome_Completo\": \"SIRLANE ALVES DA ROCHA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SIRLANE ROCHA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000886148, \"Nome_Completo\": \"SOLANGE BRITES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SOLANGE BRITES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002234, \"Nome_Completo\": \"SOLON PEREIRA DE MATOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SOLON MATOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704180, \"Nome_Completo\": \"SONEIDE SOARES DA SILVA DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SONEIDE SANTOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704097, \"Nome_Completo\": \"SONIA APARECIDA CESTILE ROSSA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SONIA ROSSA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761715, \"Nome_Completo\": \"SONIA SOARES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SONIA SOARES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001047474, \"Nome_Completo\": \"SONIA WOIEVODA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"SONIA WOIEVODA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704107, \"Nome_Completo\": \"TANIA APARECIDA DE SOUZA WICTHOFF\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"TANIA WICTHOFF\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761703, \"Nome_Completo\": \"THIAGO HENRIQUE CEZAR DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"THIAGO SANTOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704113, \"Nome_Completo\": \"TIAGO ALVES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"TIAGO ALVES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000803040, \"Nome_Completo\": \"UBIRAJARA GOMES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"UBIRAJARA GOMES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685752, \"Nome_Completo\": \"VALDECI DE ANDRADE\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"PASTOR VALDECI\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704244, \"Nome_Completo\": \"VALDECI ZESINANDO DE OLIVEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VALDECI\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002237, \"Nome_Completo\": \"VALDECIR WANDEMBRUCK BISCOTTO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VALDECIR BISCOTTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000685745, \"Nome_Completo\": \"VALDEMIR DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VALDEMIR SILVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915934, \"Nome_Completo\": \"VALDIR OSVALDO DE SOUZA\", \"Cargo\": \"PREFEITO\", \"Apelido\": \"VALDIR NEGÃO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761716, \"Nome_Completo\": \"VALDIR SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VALDIR SANTOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048535, \"Nome_Completo\": \"VALDIVINO TEIXEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VALDIVINO TEIXEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704170, \"Nome_Completo\": \"VALMIR SOARES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VALMIR SOARES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704234, \"Nome_Completo\": \"VALMIR SOARES MACIEL\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VALMIR NANICO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137897, \"Nome_Completo\": \"VALTER APARECIDO FARFUS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VALTER FARFUS\"},\n",
    "    {\"SQ_CANDIDATO\": 160000803041, \"Nome_Completo\": \"VANDERLEI DE FREITAS BANDEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VANDERLEI BANDEIRA\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761712, \"Nome_Completo\": \"VANDERLEI DOS SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VANDERLEI SANTOS\"},\n",
    "    {\"SQ_CANDIDATO\": 160001137901, \"Nome_Completo\": \"VANDERLEI RAMOS DA SILVA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VANDERLEI SILVA\"},\n",
    "    {\"SQ_CANDIDATO\": 160001138587, \"Nome_Completo\": \"VANDERLEIA MARIA GONÇALVES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VANDERLEIA GONÇALVES\"},\n",
    "    {\"SQ_CANDIDATO\": 160001047470, \"Nome_Completo\": \"VILMAR LEONEL BABIO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VILMAR BABIO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802927, \"Nome_Completo\": \"VILSON FRIES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"VILSON FRIES\"},\n",
    "    {\"SQ_CANDIDATO\": 160000803043, \"Nome_Completo\": \"WAGNER MODESTO BATISTA DE OLIVEIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"WAGNER MODESTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000704101, \"Nome_Completo\": \"WAGNER MURILO BATISTA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"WAGNER MURILO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000947236, \"Nome_Completo\": \"WAGNER ROBERTO PEREIRA MORAES\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"WAGNER ROBERTO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000802926, \"Nome_Completo\": \"WAILTON LEONEL\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"WAILTON LEONEL\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915942, \"Nome_Completo\": \"WALTER FORTUNATO DO PRADO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"WALTER FORTUNATO\"},\n",
    "    {\"SQ_CANDIDATO\": 160000915945, \"Nome_Completo\": \"WALTER LEAL\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"WALTER LEAL\"},\n",
    "    {\"SQ_CANDIDATO\": 160000761710, \"Nome_Completo\": \"WELITON SANTOS FIGUEIREDO\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"WELITON\"},\n",
    "    {\"SQ_CANDIDATO\": 160001270474, \"Nome_Completo\": \"WILIAN ROBSON PEREIRA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"WILIAN ROBSON\"},\n",
    "    {\"SQ_CANDIDATO\": 160001048610, \"Nome_Completo\": \"WILLIAM SODRE FRANCISCO\", \"Cargo\": \"VICE-PREFEITO\", \"Apelido\": \"WILLIAM FRANCISCO\"},\n",
    "    {\"SQ_CANDIDATO\": 160001002236, \"Nome_Completo\": \"WILLIAN SAUERBIER SANTOS\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"WILLIAN SAUERBIER\"},\n",
    "    {\"SQ_CANDIDATO\": 160001257175, \"Nome_Completo\": \"YASMIN DE FATIMA BIANA DOMINICO DA VEIGA\", \"Cargo\": \"VEREADOR\", \"Apelido\": \"YASMIN DOMINICO\"}\n",
    "]"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
